### ISSUE TITLE
Using sprintf instead of parameterized SQL

### ISSUE THREAD

**Issue by schatto1** [susom/realtime-randomization#3]
Hi @123andy , thanks for your work on this EM. Is there a reason you use sprintf to construct the SQL query instead of using the query method available in the framework? This was one of the things our senior developer pointed out when running a security check on this module (we're hoping to use this module on our instance here at Utah).

Thanks!

**Comment by 123andy** [comment]
I wrote this em before the framework supported the parameterized queries, I think.   I haven't refactored everything to keep up.  You are welcome to submit a pull request with a refactored code using the new parameterize methods.  I do try to use those when I write EMs today.  That said, I think the inputs to those queries are all internally generated through 'trusted' sources and are not susceptible to injection for the most part...  Thanks!

**Comment by schatto1** [comment]
Thanks for your response @123andy - already made the changes for our REDCap instance so happy to create a pull request. I cleaned up the code a bit but here it is: https://github.com/susom/realtime-randomization/pull/4

Thanks again!
