### ISSUE TITLE
Fail to randomize when leaving empty fields

### ISSUE THREAD

**Issue by CorentinWicht** [susom/realtime-randomization#7]
REDCap 13.7.17 · PHP 8.0.27 (Linux/Unix OS) · MariaDB 10.5.16
----

Dear Susom,

I am trying your very nice EM and found a weird behaviour:

I have configured the module as such (very simple configuration):
![image](https://github.com/susom/realtime-randomization/assets/52161904/1f39b88c-8569-4acb-9133-8a5bb2c0af16)

I have also uploaded an allocation table in the "Randomization" tab.

Online randomization works if I fill in each field (none of them are required fields):
![image](https://github.com/susom/realtime-randomization/assets/52161904/3a4ccc03-7430-4c15-8c8b-e33f50cd90d3)
![image](https://github.com/susom/realtime-randomization/assets/52161904/6632b2ca-ef37-4179-8309-54722934568d)

But randomization fails if I leave at least of the field empty:
![image](https://github.com/susom/realtime-randomization/assets/52161904/4e3fb468-2bd6-4921-93e0-72be63789e03)
![image](https://github.com/susom/realtime-randomization/assets/52161904/7b107b1a-bb2e-4f58-8e98-801c1f259a0f)

I realized that the problem is the same if I choose other randomization triggers, e.g., Trigger logic such as `[ic_yn]='1'` or Trigger Event set to `Arm 1 - Screening`.

**Do you have any idea why this is happening?** 

Unfortunately it makes your EM currently unusable as missing data are inevitable in research projects...

For replication purpose, you can download my test project here (based on REDCap Randomized Clinical Trial template):
https://kdrive.infomaniak.com/app/share/718010/5bb3dc01-88e2-4057-8b54-3a7937d97fc9

**Comment by 123andy** [comment]
@CorentinWicht - does your randomization include any strata?  Can you show your randomization allocations?  Are there any messages in the project logs after saving a new record?  You have to also be sure to have a newly named record to take another allocation in testing.

**Comment by CorentinWicht** [comment]
> @CorentinWicht - does your randomization include any strata? Can you show your randomization allocations? Are there any messages in the project logs after saving a new record? You have to also be sure to have a newly named record to take another allocation in testing.

Dear @123andy many thanks for your prompt reply.
Here is the randomization model:
![image](https://github.com/susom/realtime-randomization/assets/52161904/44917cb4-b835-4c5a-8e0f-581a7ba7ba27)

And the allocation table which is simply the one suggested by REDCap when you click on "Example #3 (5x all possible combos)" under STEP 2 in the Randomization setup:
![image](https://github.com/susom/realtime-randomization/assets/52161904/66d919e7-1f2d-415d-8c09-36357a421b71)

Here is what's logged (in the project log) when I create a new record (with missing data for the "gender" field):
![image](https://github.com/susom/realtime-randomization/assets/52161904/52b1d1da-90e5-492d-901f-4c96a03bf3a6)

And this is what happens when I update the record and add data to the "gender" field:
![image](https://github.com/susom/realtime-randomization/assets/52161904/b0535fac-3939-4307-8483-88356419cf5d)

You can clearly see that the randomization is only triggered when the Demographics instrument is filled entirely.

--- 
**Still I believe I have found the error**:
Since "gender" and "race" fields are part of the randomization model (as stratification factors) the randomization allocation is not happening hence the issue is not related to your module but would also happen if I manually press on REDCap "randomize" button. 

My apologies for the misunderstanding

**Comment by 123andy** [comment]
Great.  I’m glad you figured it out.  Strata are indeed required.
________________________________
