### ISSUE TITLE
Release for v14 support

### ISSUE THREAD

**Issue by lsgs** [susom/realtime-randomization#8]
@ihabzee please can you do a new release for the official REDCap repo? The latest official release there is v1.0.2, which does not work with projects created on REDCap v14+ (i.e. with the new `redcap_dataX` tables). Thanks!

**Comment by ihabzee** [comment]
Hi @lsgs I submitted a new release to the community. I will keep you posted when this is published. 

Thanks.

**Comment by lsgs** [comment]
Perfect @ihabzee! Thanks very much for your prompt action!
